# Generated by Django 2.1.5 on 2019-06-10 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateRatio',
            fields=[
                ('rate_ratio_date', models.DateField(primary_key=True, serialize=False)),
                ('rate_ratio', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('h10_id', models.CharField(max_length=25, unique=True)),
                ('country_name', models.CharField(max_length=25)),
                ('short_name', models.CharField(max_length=10)),
                ('flag_image_file_name', models.CharField(max_length=64)),
                ('currency_name', models.CharField(max_length=20)),
                ('currency_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_date', models.DateField()),
                ('per_dollar', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.Currency')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('currency', 'rate_date')},
        ),
    ]
